# Generated by Django 5.0.1 on 2024-04-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientnotification',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientnotification',
            name='is_declined',
            field=models.BooleanField(default=False),
        ),
    ]
