# Generated by Django 5.0.1 on 2024-03-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_verified_customuser_verification_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='number_of_children',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
