# Generated by Django 5.0.1 on 2024-03-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_parent_number_of_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Parent'), ('T', 'Tutor')], max_length=10),
        ),
    ]
