# Generated by Django 5.0.1 on 2024-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_major_student_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
