# Generated by Django 5.0.1 on 2024-03-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_parent_password_remove_student_password_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
