# Generated by Django 5.0.1 on 2024-03-30 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
