# Generated by Django 5.0.1 on 2024-04-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='cv',
        ),
    ]
