# Generated by Django 5.0.1 on 2024-04-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_customuser_bio_customuser_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role2',
            field=models.CharField(choices=[('T', 'Tutor')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Parent')], max_length=10),
        ),
    ]
