# Generated by Django 5.0.1 on 2024-04-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_customuser_role2_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cv',
            field=models.FileField(blank=True, upload_to='cv/'),
        ),
    ]
