# Generated by Django 5.0.1 on 2024-04-04 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_remove_customuser_role2_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='virtual',
        ),
        migrations.AddField(
            model_name='tutor',
            name='cv',
            field=models.FileField(default=0, upload_to='cv/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='full_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone_number',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='role',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='level',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='uni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='working_days',
            field=models.CharField(max_length=255),
        ),
    ]
