# Generated by Django 5.0.1 on 2024-04-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_remove_tutor_description_remove_tutor_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Parent'), ('T', 'Tutor')], max_length=10),
        ),
    ]
