# Generated by Django 5.0.1 on 2024-04-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_tutor_is_active_alter_tutor_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='password',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='username',
        ),
    ]
