# Generated by Django 5.0.1 on 2024-04-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_remove_tutor_email_remove_tutor_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='is_active',
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='role',
            field=models.CharField(max_length=100),
        ),
    ]
