# Generated by Django 5.0.1 on 2024-04-05 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_remove_student_user_client_delete_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='education',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='uni',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='virtual',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='working_days',
        ),
    ]
