# Generated by Django 5.0.1 on 2024-04-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_customuser_bio_remove_customuser_cv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='role',
        ),
    ]
