# Generated by Django 5.0.1 on 2024-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_client_email_client_full_name_client_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('P', 'Parent'), ('T', 'Tutor')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
