# Generated by Django 5.0.1 on 2024-04-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_client_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
        migrations.RemoveField(
            model_name='client',
            name='username',
        ),
    ]
