# Generated by Django 5.0.1 on 2024-04-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_remove_client_email_remove_client_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default=0, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.CharField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
