# Generated by Django 5.0.1 on 2024-04-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='username',
        ),
    ]
