# Generated by Django 5.0.1 on 2024-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_remove_client_email_remove_client_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='tutor_profiles/'),
        ),
    ]
