# Generated by Django 5.0.1 on 2024-04-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_tutor_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='profile_image',
            new_name='profile',
        ),
    ]
